#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Unified SCET RAG Q&A script (offline retrieval + optional LLM generation).

Capabilities:
- Local vector DB + BM25 hybrid retrieval
- Offline extractive answering (mode=offline)
- LLM generative answering (mode=llm)
- Optional HTTP service (--serve)

Default index directory (generated by build_scet_rag_index.py):
rag_index_scet/
  - index.faiss
  - chunks.jsonl
  - bm25_tokens.jsonl
  - manifest.json

Examples:

Online:
    python rag_scet_qa.py --question "MCTP bridge does not work. What is the root cause? What are the next troubleshooting steps?" --top-k 10

Offline:
    python rag_scet_qa.py --question "MCTP bridge does not work. What is the root cause? What are the next troubleshooting steps?" --top-k 10 --mode offline

python rag_scet_qa.py --serve --mode llm --host 0.0.0.0 --port 8000
"""

import argparse
import json
import os
import re
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import faiss
import numpy as np
import openai
from sentence_transformers import SentenceTransformer


ENV_LLM_GATEWAY_API_URL = "LLM_GATEWAY_API_URL"
ENV_LLM_GATEWAY_API_TOKEN = "LLM_GATEWAY_API_TOKEN"
DEFAULT_MODEL = "gpt-5-mini"
DEFAULT_MAX_TOKENS = 2000


def tokenize_for_bm25(text: str) -> List[str]:
    text = text.lower()
    en_tokens = re.findall(r"[a-z0-9_]+", text)
    zh_chars = re.findall(r"[\u4e00-\u9fff]", text)
    return en_tokens + zh_chars


def extract_priority_keywords(query: str) -> List[str]:
    """
    Extract strong semantic keywords from the query (e.g., MCTP/PCIe/SMBus) for reranking.
    """
    kws = re.findall(r"[A-Za-z][A-Za-z0-9_\-]{2,}", query)
    uniq: List[str] = []
    seen = set()
    for k in kws:
        lk = k.lower()
        if lk in seen:
            continue
        seen.add(lk)
        uniq.append(lk)
    return uniq


def bm25_idf_and_tf(docs_tokens: List[List[str]]) -> Tuple[Dict[str, float], List[Dict[str, int]], float]:
    n_docs = len(docs_tokens)
    tf_list: List[Dict[str, int]] = []
    df: Dict[str, int] = {}
    total_len = 0

    for tokens in docs_tokens:
        total_len += len(tokens)
        tf: Dict[str, int] = {}
        seen = set()
        for t in tokens:
            tf[t] = tf.get(t, 0) + 1
            if t not in seen:
                df[t] = df.get(t, 0) + 1
                seen.add(t)
        tf_list.append(tf)

    avgdl = total_len / n_docs if n_docs else 0.0
    idf: Dict[str, float] = {}
    for term, df_t in df.items():
        idf[term] = float(np.log(1.0 + (n_docs - df_t + 0.5) / (df_t + 0.5)))
    return idf, tf_list, avgdl


def bm25_score_query(
    query_tokens: List[str],
    idf: Dict[str, float],
    tf_list: List[Dict[str, int]],
    doc_lens: List[int],
    avgdl: float,
    k1: float = 1.5,
    b: float = 0.75,
) -> np.ndarray:
    scores = np.zeros(len(tf_list), dtype=np.float32)
    if not query_tokens:
        return scores

    q_terms: Dict[str, int] = {}
    for t in query_tokens:
        q_terms[t] = q_terms.get(t, 0) + 1

    for i, tf in enumerate(tf_list):
        dl = doc_lens[i] if i < len(doc_lens) else 0
        denom_norm = k1 * (1.0 - b + b * (dl / avgdl if avgdl > 0 else 0.0))
        score = 0.0
        for term in q_terms.keys():
            if term not in tf:
                continue
            f = tf[term]
            term_idf = idf.get(term, 0.0)
            score += term_idf * (f * (k1 + 1.0)) / (f + denom_norm)
        scores[i] = score
    return scores


def minmax_norm(arr: np.ndarray) -> np.ndarray:
    if arr.size == 0:
        return arr
    a_min = float(arr.min())
    a_max = float(arr.max())
    if a_max - a_min < 1e-9:
        return np.zeros_like(arr)
    return (arr - a_min) / (a_max - a_min)


def trim_text(text: str, max_len: int = 480) -> str:
    t = text.strip().replace("\r", "\n")
    t = re.sub(r"\n{3,}", "\n\n", t)
    if len(t) <= max_len:
        return t
    return t[:max_len] + " ..."


class RagEngine:
    def __init__(self, args: argparse.Namespace):
        self.args = args

        index_dir = Path(args.index_dir)
        manifest_path = index_dir / "manifest.json"
        chunks_path = index_dir / "chunks.jsonl"
        bm25_tokens_path = index_dir / "bm25_tokens.jsonl"
        faiss_path = index_dir / "index.faiss"

        if not manifest_path.exists() or not chunks_path.exists() or not bm25_tokens_path.exists() or not faiss_path.exists():
            raise FileNotFoundError("Index files are incomplete. Please run build_scet_rag_index.py first.")

        self.manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        self.index = faiss.read_index(str(faiss_path))

        self.embedding_model = args.embedding_model or self.manifest.get("embedding_model", "BAAI/bge-small-zh-v1.5")
        print(f"Loading local embedding model: {self.embedding_model}")
        self.embedder = SentenceTransformer(self.embedding_model)

        self.chunks: List[Dict[str, Any]] = []
        with chunks_path.open("r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line:
                    self.chunks.append(json.loads(line))

        self.doc_tokens: List[List[str]] = []
        with bm25_tokens_path.open("r", encoding="utf-8") as f:
            for line in f:
                obj = json.loads(line)
                self.doc_tokens.append(obj.get("tokens", []))

        if len(self.chunks) != len(self.doc_tokens):
            raise ValueError("chunks and bm25_tokens have inconsistent lengths")

        self.doc_lens = [len(t) for t in self.doc_tokens]
        self.idf, self.tf_list, self.avgdl = bm25_idf_and_tf(self.doc_tokens)

    def embed_query(self, query: str) -> np.ndarray:
        vec = self.embedder.encode(
            [query],
            normalize_embeddings=True,
            convert_to_numpy=True,
        ).astype(np.float32)
        return vec

    def hybrid_retrieve(self, query: str, top_k: int = 8) -> List[Dict[str, Any]]:
        qvec = self.embed_query(query)

        vec_scores, vec_ids = self.index.search(qvec, min(max(top_k * 5, 20), len(self.chunks)))
        vec_scores = vec_scores[0]
        vec_ids = vec_ids[0]

        vec_full = np.zeros(len(self.chunks), dtype=np.float32)
        for s, i in zip(vec_scores, vec_ids):
            if i >= 0:
                vec_full[i] = max(vec_full[i], float(s))

        q_tokens = tokenize_for_bm25(query)
        bm25_full = bm25_score_query(q_tokens, self.idf, self.tf_list, self.doc_lens, self.avgdl)

        vec_n = minmax_norm(vec_full)
        bm_n = minmax_norm(bm25_full)
        alpha = self.args.vector_weight
        final_scores = alpha * vec_n + (1.0 - alpha) * bm_n

        # Keyword-priority reranking: reduce false positives with similar semantics but mismatched domain terms
        priority_kws = extract_priority_keywords(query)
        if priority_kws:
            kw_hits = np.zeros(len(self.chunks), dtype=np.float32)
            for i, c in enumerate(self.chunks):
                text = str(c.get("text", "")).lower()
                hit = 0
                for kw in priority_kws:
                    if kw in text:
                        hit += 1
                kw_hits[i] = float(hit)

            kw_n = minmax_norm(kw_hits)
            final_scores = final_scores + float(self.args.keyword_boost) * kw_n

            # If keyword-hit docs exist, rank them before non-hit docs
            has_kw_mask = kw_hits > 0
            if np.any(has_kw_mask):
                ranked_ids = np.argsort(-final_scores)
                hit_ids = [idx for idx in ranked_ids if has_kw_mask[idx]]
                non_hit_ids = [idx for idx in ranked_ids if not has_kw_mask[idx]]
                top_ids = np.array((hit_ids + non_hit_ids)[:top_k], dtype=np.int64)
            else:
                top_ids = np.argsort(-final_scores)[:top_k]
        else:
            top_ids = np.argsort(-final_scores)[:top_k]
        display_scores = minmax_norm(final_scores)

        results: List[Dict[str, Any]] = []
        for rank, idx in enumerate(top_ids, start=1):
            c = self.chunks[int(idx)]
            results.append(
                {
                    "rank": rank,
                    "id": int(idx),
                    "score": float(display_scores[idx]),
                    "raw_score": float(final_scores[idx]),
                    "vector_score": float(vec_full[idx]),
                    "bm25_score": float(bm25_full[idx]),
                    "text": c.get("text", ""),
                    "meta": c.get("meta", {}),
                }
            )
        return results


def extract_issue_key_from_question(question: str) -> Optional[str]:
    m = re.search(r"\b(SCET-\d+)\b", question, flags=re.IGNORECASE)
    if not m:
        return None
    return m.group(1).upper()


def build_exact_issue_contexts(engine: RagEngine, issue_key: str, limit: int) -> List[Dict[str, Any]]:
    exact: List[Dict[str, Any]] = []
    for idx, c in enumerate(engine.chunks):
        meta = c.get("meta", {}) or {}
        key = str(meta.get("issue_key", "")).upper()
        if key != issue_key:
            continue
        exact.append(
            {
                "rank": 0,
                "id": int(idx),
                "score": 1.0,
                "vector_score": 0.0,
                "bm25_score": 0.0,
                "text": c.get("text", ""),
                "meta": meta,
            }
        )
        if len(exact) >= limit:
            break
    return exact


def merge_contexts_with_exact_issue(
    retrieved: List[Dict[str, Any]],
    exact: List[Dict[str, Any]],
    top_k: int,
) -> List[Dict[str, Any]]:
    merged: List[Dict[str, Any]] = []
    seen_ids = set()

    for c in exact + retrieved:
        cid = c.get("id")
        if cid in seen_ids:
            continue
        seen_ids.add(cid)
        merged.append(c)
        if len(merged) >= top_k:
            break
    return merged


def extract_ticket_title_from_context_text(text: str) -> str:
    if not text:
        return ""
    m = re.search(r"^summary:\s*(.+)$", text, flags=re.IGNORECASE | re.MULTILINE)
    if m:
        return m.group(1).strip()
    return ""


def extract_ticket_title_from_source_file(source_file: str) -> str:
    if not source_file:
        return ""
    try:
        fp = Path(source_file)
        if not fp.exists():
            fp = Path(source_file.replace("/", os.sep))
        if not fp.exists():
            return ""

        data = json.loads(fp.read_text(encoding="utf-8"))
        issue = data.get("issue", {}) if isinstance(data, dict) else {}
        fields = issue.get("fields", {}) if isinstance(issue, dict) else {}
        summary = fields.get("summary")
        if isinstance(summary, str) and summary.strip():
            return summary.strip()
    except Exception:
        return ""
    return ""


def build_sources(contexts: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    sources: List[Dict[str, Any]] = []
    title_cache: Dict[str, str] = {}

    for i, c in enumerate(contexts, start=1):
        meta = c.get("meta", {}) or {}
        text = c.get("text", "") or ""
        source_path = str(meta.get("source_file", "") or "")

        if source_path in title_cache:
            ticket_title = title_cache[source_path]
        else:
            ticket_title = extract_ticket_title_from_source_file(source_path)
            if not ticket_title:
                ticket_title = extract_ticket_title_from_context_text(text)
            title_cache[source_path] = ticket_title

        sources.append(
            {
                "ref": i,
                "issue_key": meta.get("issue_key"),
                "source_file": ticket_title or "Untitled",
                "issue_url": meta.get("issue_url"),
                "score": c.get("score"),
            }
        )
    return sources


def build_contexts_for_prompt(contexts: List[Dict[str, Any]], snippet_max_len: int) -> str:
    lines: List[str] = []
    for i, c in enumerate(contexts, start=1):
        meta = c.get("meta", {}) or {}
        issue_key = meta.get("issue_key", "")
        issue_url = meta.get("issue_url", "")
        source_file = meta.get("source_file", "")
        score = c.get("score", 0.0)
        snippet = trim_text(c.get("text", ""), max_len=snippet_max_len)

        lines.append(f"[{i}] issue_key: {issue_key}")
        lines.append(f"score: {score:.6f}")
        lines.append(f"issue_url: {issue_url}")
        lines.append(f"source_file: {source_file}")
        lines.append("context:")
        lines.append(snippet)
        lines.append("")
    return "\n".join(lines).strip()


def synthesize_extractive_answer(question: str, contexts: List[Dict[str, Any]], snippet_max_len: int) -> str:
    if not contexts:
        return "The knowledge base does not cover this question."

    lines = [f"Question: {question}", "Possible relevant information from retrieved knowledge base snippets:"]
    for i, c in enumerate(contexts, start=1):
        snippet = trim_text(c.get("text", ""), max_len=snippet_max_len)
        lines.append(f"[{i}] {snippet}")
    lines.append("Note: This is an offline extractive answer (no online generation model was called).")
    return "\n".join(lines)


def create_client(
    gateway_key: Optional[str] = None,
    base_url: Optional[str] = None,
    user_name: Optional[str] = None,
) -> openai.OpenAI:
    key = (gateway_key or os.getenv(ENV_LLM_GATEWAY_API_TOKEN) or "").strip()
    if not key:
        raise RuntimeError(f"Missing required environment variable: {ENV_LLM_GATEWAY_API_TOKEN}")

    resolved_base_url = (base_url or os.getenv(ENV_LLM_GATEWAY_API_URL) or "").strip()
    if not resolved_base_url:
        raise RuntimeError(f"Missing required environment variable: {ENV_LLM_GATEWAY_API_URL}")

    # os.getlogin() may raise FileNotFoundError in no-TTY environments
    # Use a robust fallback to avoid runtime crashes
    user = user_name or os.getenv("LLM_USER") or os.getenv("USER") or os.getenv("USERNAME")
    if not user:
        try:
            user = os.getlogin()
        except Exception:
            user = "unknown-user"

    return openai.OpenAI(
        base_url=resolved_base_url,
        api_key="dummy",
        default_headers={
            "Ocp-Apim-Subscription-Key": key,
            "user": user,
        },
    )


def chat_completion(
    messages: List[Dict[str, str]],
    model: str = DEFAULT_MODEL,
    max_tokens: int = DEFAULT_MAX_TOKENS,
    gateway_key: Optional[str] = None,
    base_url: Optional[str] = None,
    user_name: Optional[str] = None,
) -> Dict[str, Any]:
    client = create_client(gateway_key=gateway_key, base_url=base_url, user_name=user_name)
    response = client.chat.completions.create(
        model=model,
        max_tokens=max_tokens,
        messages=messages,
    )

    content = ""
    if response.choices and response.choices[0].message:
        content = response.choices[0].message.content or ""

    return {
        "model": model,
        "content": content,
        "raw": response.model_dump() if hasattr(response, "model_dump") else response,
    }


def build_llm_messages(question: str, context_text: str) -> List[Dict[str, str]]:
    system_prompt = (
        "You are the SCET knowledge-base analysis assistant. "
        "You must answer strictly based on the provided retrieved context and must not fabricate information. "
        "Answer format requirements:\n"
        "1) Start with a concise conclusion\n"
        "2) Then provide evidence (cite [index])\n"
        "3) Then provide possible root causes and next troubleshooting steps\n"
        "4) If evidence is insufficient, explicitly state: 'Insufficient knowledge base evidence.'"
    )

    user_prompt = (
        f"User question:\n{question}\n\n"
        f"Local vector database retrieval results:\n{context_text}\n\n"
        "Please analyze and answer based on the above content."
    )

    return [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt},
    ]


def retrieve_contexts(engine: RagEngine, question: str, top_k: int) -> List[Dict[str, Any]]:
    contexts = engine.hybrid_retrieve(question, top_k=top_k)

    target_issue_key = extract_issue_key_from_question(question)
    if target_issue_key:
        exact_contexts = build_exact_issue_contexts(engine, target_issue_key, limit=top_k)
        contexts = merge_contexts_with_exact_issue(contexts, exact_contexts, top_k=top_k)

    return contexts


def answer_offline(engine: RagEngine, args: argparse.Namespace, question: str) -> Dict[str, Any]:
    contexts = retrieve_contexts(engine, question, top_k=args.top_k)
    answer_text = synthesize_extractive_answer(question, contexts, snippet_max_len=args.snippet_max_len)
    return {
        "question": question,
        "answer": answer_text,
        "sources": build_sources(contexts),
        "mode": "offline",
    }


def answer_llm(engine: RagEngine, args: argparse.Namespace, question: str) -> Dict[str, Any]:
    contexts = retrieve_contexts(engine, question, top_k=args.top_k)

    if not contexts:
        return {
            "question": question,
            "answer": "The knowledge base does not cover this question (no valid context was retrieved).",
            "sources": [],
            "mode": "rag+llm",
        }

    context_text = build_contexts_for_prompt(contexts, args.snippet_max_len)
    messages = build_llm_messages(question, context_text)
    llm_result = chat_completion(
        messages=messages,
        model=args.model,
        max_tokens=args.max_tokens,
        gateway_key=args.gateway_key or None,
        user_name=args.user or None,
    )

    return {
        "question": question,
        "answer": llm_result.get("content", ""),
        "sources": build_sources(contexts),
        "mode": "rag+llm",
        "llm_model": llm_result.get("model"),
    }


def build_arg_parser(default_mode: str = "llm") -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="SCET RAG Q&A (unified: offline / llm)")
    parser.add_argument("--mode", choices=["llm", "offline"], default=default_mode, help="Answer mode")
    parser.add_argument("--index-dir", default="rag_index_scet", help="Index directory")
    parser.add_argument("--question", default="", help="Single question input")
    parser.add_argument("--top-k", type=int, default=10, help="Number of retrieved contexts")
    parser.add_argument("--vector-weight", type=float, default=0.65, help="Vector score weight (0~1)")
    parser.add_argument("--keyword-boost", type=float, default=0.35, help="Keyword-hit boost (higher -> stronger keyword preference)")
    parser.add_argument("--embedding-model", default="", help="Local embedding model name (empty -> read from manifest)")
    parser.add_argument("--snippet-max-len", type=int, default=480, help="Max display chars per snippet in answer")

    parser.add_argument("--model", default=DEFAULT_MODEL, help="LLM model name (effective in mode=llm)")
    parser.add_argument("--max-tokens", type=int, default=DEFAULT_MAX_TOKENS, help="LLM max output tokens")
    parser.add_argument("--gateway-key", default="", help="Gateway subscription key (empty -> env LLM_GATEWAY_API_TOKEN)")
    parser.add_argument("--user", default="", help="Request header user (empty -> auto-resolve)")

    parser.add_argument("--serve", action="store_true", help="Start HTTP service")
    parser.add_argument("--host", default="127.0.0.1", help="Service bind host")
    parser.add_argument("--port", type=int, default=8000, help="Service port")
    return parser


def ask_scet_rag(
    question: str,
    mode: str = "llm",
    index_dir: str = "rag_index_scet",
    top_k: int = 11,
    vector_weight: float = 0.65,
    keyword_boost: float = 0.35,
    snippet_max_len: int = 480,
    model: str = DEFAULT_MODEL,
    max_tokens: int = DEFAULT_MAX_TOKENS,
    base_url: Optional[str] = None,
    gateway_key: str = "",
    user: str = "",
    embedding_model: str = "",
) -> Dict[str, Any]:
    """
    Programmatic API for direct use by other modules.
    Runs SCET RAG Q&A on one question and returns a structured result dict.
    """
    parser = build_arg_parser(default_mode=mode)
    args = parser.parse_args([])

    args.mode = mode
    args.index_dir = index_dir
    args.top_k = top_k
    args.vector_weight = vector_weight
    args.keyword_boost = keyword_boost
    args.snippet_max_len = snippet_max_len
    args.model = model
    args.max_tokens = max_tokens
    args.base_url = (base_url or os.getenv(ENV_LLM_GATEWAY_API_URL) or "").strip()
    if args.mode == "llm" and not args.base_url:
        raise RuntimeError(f"Missing required environment variable: {ENV_LLM_GATEWAY_API_URL}")
    args.gateway_key = gateway_key
    args.user = user
    args.embedding_model = embedding_model

    engine = RagEngine(args)
    if args.mode == "llm":
        return answer_llm(engine, args, question)
    return answer_offline(engine, args, question)


def run_rag_scet_qa(default_mode: str = "llm") -> int:
    parser = build_arg_parser(default_mode=default_mode)
    args = parser.parse_args()

    args.base_url = (os.getenv(ENV_LLM_GATEWAY_API_URL) or "").strip()
    if args.mode == "llm" and not args.base_url:
        raise RuntimeError(f"Missing required environment variable: {ENV_LLM_GATEWAY_API_URL}")

    engine = RagEngine(args)

    def ask_once(q: str) -> Dict[str, Any]:
        if args.mode == "llm":
            return answer_llm(engine, args, q)
        return answer_offline(engine, args, q)

    if args.serve:
        from fastapi import FastAPI
        from pydantic import BaseModel
        import uvicorn

        class AskReq(BaseModel):
            question: str

        app = FastAPI(title="SCET Unified RAG QA API")

        @app.get("/health")
        def health() -> Dict[str, Any]:
            return {
                "ok": True,
                "index_dir": args.index_dir,
                "chunks": len(engine.chunks),
                "mode": args.mode,
            }

        @app.post("/ask")
        def ask(req: AskReq) -> Dict[str, Any]:
            return ask_once(req.question)

        uvicorn.run(app, host=args.host, port=args.port)
        return 0

    if not args.question.strip():
        print("Please pass a question via --question, or use --serve to start the HTTP service.")
        return 1

    print(json.dumps(ask_once(args.question), ensure_ascii=False, indent=2))
    return 0


def run_cli(default_mode: str = "llm") -> int:
    return run_rag_scet_qa(default_mode=default_mode)


def main() -> int:
    return run_rag_scet_qa(default_mode="llm")


if __name__ == "__main__":
    raise SystemExit(main())
